Cache logs
yahoo/fili pull request #1114
Opened 2020-11-17 17:14 UTC by bharatmotwani

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-11-17 21:37 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardCacheInfo.java
> +        this.cacheValLength = cacheValLength;
cacheKey Length as well

2020-11-17 21:40 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardCacheInfo.java
> +        this.cacheKey = cacheKey;
Maybe the first 50 and last fifty of the query?

2020-11-18 17:04 UTC, michael-mclawhorn requested changes
I would look to improve the specificity on the checksum building exception block.
Needs Changelog and Tests.

2020-11-18 20:58 UTC, bharatmotwani commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/CacheV2ResponseProcessor.java
> +        } catch (Exception ex) {
Nothing intresting , I just made it throw RunTimeException

2020-11-19 00:40 UTC, michael-mclawhorn approved these changes

2020-11-19 00:44 UTC, michael-mclawhorn reviewed
I'm approving this for expediency, but I want tests around the new behaviors including the config controlled behavior.  
Also, the MD5Checksum code would probably work better as an injectable so that it's easier to mock and test.

2020-11-19 00:45 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/CacheV2ResponseProcessor.java
> +                //mark and log the cache put failure
This could use a test.

2020-11-19 00:45 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/responseprocessors/CacheV2ResponseProcessor.java
> +    public static String getMD5Cksum(String cacheKey) {
This would be better injected.

2020-11-19 00:45 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/util/QuerySignedCacheService.java
> +                CACHE_SET_FAILURES.mark(1);
This could use a test.

2020-11-19 00:46 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/data/cache/MemDataCache.java
> +                return client.set(key, expirationInSeconds, value) != null;
These two paths could use a test to guarantee config results in the correct behaviors.

2020-11-19 00:48 UTC, merged