Add more cache logging to track get or put success.
yahoo/fili pull request #1118
Opened 2020-12-02 23:50 UTC by bharatmotwani

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-12-03 16:36 UTC, michael-mclawhorn requested changes
I think I'd like a test that captures the serialization of the new BardCacheInfo.  You can probably build an instance by hand and push it through an ObjectMapper.writer() to get the relevant string for testing.

2020-12-03 16:36 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/util/QuerySignedCacheService.java
> +                            CacheV2ResponseProcessor.getMD5Cksum(getKey(druidQuery)),
when we're doing a CacheV2 Response processor, we should capture a checksum of the cache signature as well.

2020-12-03 16:36 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/util/QuerySignedCacheService.java
> +                                    CacheV2ResponseProcessor.getMD5Cksum(cacheKey),
Let's capture cache signature where we can.

2020-12-03 16:36 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/util/QuerySignedCacheService.java
> +                                LOG_CACHE_POTENTIAL_HIT,
Let's rename this to 'signature mismatch'

2020-12-04 17:53 UTC, bharatmotwani commented
Logging test on dev1 UAD host.

[https://splunk.insights.yahoo.com/splunk/en-US/app/search/search?earliest=-15m&latest=now&q=search%20index%3Duad_index%20eventtype%20%3D%20%22Bard%20Data%20Requests%22%20host%3D%22dev-web1.uad.bf2.yahoo.com%22&sid=1607104063.442264_8C4C1C06-8E41-40DB-86F8-8DE3A8EA8C47&display.page.search.mode=verbose&dispatch.sample_ratio=1]

2020-12-07 20:11 UTC, michael-mclawhorn reviewed
Per discussion we're not able to use the cachePutStats so we should prune it out.

2020-12-07 20:11 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardQueryInfo.java
> +    private Map<String, BardCacheInfo> putCacheStatsMap = new HashMap<>();
Per discussion, remove putCacheStats (because cache put happens after return so we'll never have cache put data)

2020-12-07 20:11 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardQueryInfo.java
> +        getBardQueryInfo().putCacheStatsMap.put(cksum, infoLog);
Because this happens after the query has been returned this can't be useful.

2020-12-07 20:11 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardQueryInfo.java
> +        return putCacheStatsMap.values();
Remove (as discussed above)

2020-12-07 20:11 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/web/util/QuerySignedCacheService.java
> +                BardQueryInfo.getBardQueryInfo().addCachePutInfo(
This is now typically happening after query completion so the BardQueryInfo isn't useful for logging.  (and may already have been cleared)

2020-12-07 20:11 UTC, michael-mclawhorn commented on fili-core/src/test/groovy/com/yahoo/bard/webservice/logging/blocks/BardQueryInfoSpec.groovy
> +        bardQueryInfo.addCachePutInfo("test", new BardCacheInfo("setFailure", 10, "test", "testSignature",100))
remove

2020-12-09 16:51 UTC, michael-mclawhorn approved these changes

2020-12-09 16:51 UTC, merged