Add virtual columns and first last any aggregation support
yahoo/fili pull request #1139
Opened 2021-02-23 15:13 UTC by sgoplani

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-02-23 20:10 UTC, michael-mclawhorn requested changes
A few changes in virtual columns constructors.
A lot of small downstream changes in with-ers in response to the deprecation.
Also, looking at this code I wonder if we'd be well served to stop having classes for each of the aggregations and instead build some sort of 'simpleAggregator' type so we don't have to have so many classes.
That's definitely a nice to have and we don't have to do it now.  But we have now upwards of 15 classes that differ only in an internal type string.

If we were to do it, I'd make the new SimpleAggregation class, leave the existing explicit aggregation classes in, but deprecated, and then see how painful the refactor is to rip any explicit references to them out.

Like I said, not a thing we have to do now, but I have having lots of lines of classes with almost no behavioral difference between them.

2021-02-23 20:10 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/DruidAggregationQuery.java
> +
👍

2021-02-23 20:10 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/query/GroupByQuery.java
> +        super(
Same advice as above, this becomes the primary constructor and non test invocations should migrate to it.  It's ugly, but it minimizes the changes of throwing virtual columns away under copy-with-modification which we do all over the place.

2021-02-23 20:10 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/virtualcolumns/ExpressionVirtualColumn.java
> +    private final String outputType;
https://druid.apache.org/docs/latest/querying/virtual-columns.html

We might want to defensively make an inner enum for the types on the virtual column.

2021-02-24 16:50 UTC, sgoplani commented
> A few changes in virtual columns constructors.
> A lot of small downstream changes in with-ers in response to the deprecation.
> Also, looking at this code I wonder if we'd be well served to stop having classes for each of the aggregations and instead build some sort of 'simpleAggregator' type so we don't have to have so many classes.
> That's definitely a nice to have and we don't have to do it now. But we have now upwards of 15 classes that differ only in an internal type string.
> 
> If we were to do it, I'd make the new SimpleAggregation class, leave the existing explicit aggregation classes in, but deprecated, and then see how painful the refactor is to rip any explicit references to them out.
> 
> Like I said, not a thing we have to do now, but I have having lots of lines of classes with almost no behavioral difference between them.

2021-02-24 16:50 UTC, closed without merging