Log total number of rows in response
yahoo/fili pull request #1279
Opened 2022-11-11 14:54 UTC by hridaydubey

Log total number of rows in response

2022-11-16 20:43 UTC, michael-mclawhorn requested changes
Quick whitespace fix please.

2022-11-16 20:43 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardQueryInfo.java
> +        new AbstractMap.SimpleImmutableEntry<>(DRUID_RESPONSE_SIZE, druidResponseSize)
indentation needs to be fixed.

2022-11-17 15:02 UTC, hridaydubey commented on fili-core/src/main/java/com/yahoo/bard/webservice/logging/blocks/BardQueryInfo.java
> +        new AbstractMap.SimpleImmutableEntry<>(DRUID_RESPONSE_SIZE, druidResponseSize)
Fixed indentation

2022-11-17 20:49 UTC, michael-mclawhorn approved these changes

2022-11-21 16:43 UTC, merged