Fix DruidNavigator loading multiple tables
yahoo/fili pull request #309
Opened 2017-05-26 18:09 UTC by kevinhinterlong

It appears the locking mechanism was forced to time out while loading
multiple tables because the lock for getting all the tables was still active.

Now only the lock for getting all the tables (`loadAllDatasources()`) is used.

2017-05-26 18:23 UTC, cdeszaq submitted a review, later dismissed
A few things here:

1. Changelog entry needed (probably in the `Fixes` section)
2. It would be nice to have a test in place that shows the issue and that this change fixes it.
3. I'm not sure I understand how this is fixing the problem. The main change I see is to move the `get` to the caller. I don't really understand how that solves the problem which, as I understand it, is that the follow-on calls are trying to run while the 1st call isn't finished. Given how the AsyncHttpClient works, multiple calls in flight at once shouldn't be a problem. And there's no lock involved (other than the implicit one in `Future::get`), so I'm a little confused there as well.
4. Don't we still want to have the later calls timeout or at least finish executing before the rest of the application starts up? I think this change would allow the app to start w/o having any of the tables configured...

2017-06-01 18:32 UTC, michael-mclawhorn commented on fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/dimension/GenericDimensionConfigs.java
It's not clear what the String in this map is.

2017-06-01 19:22 UTC, ghost requested changes

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/test/groovy/com/yahoo/wiki/webservice/web/endpoints/MultipleDatasourceDruidConfigLoaderSpec.groovy
> +            println "No response for " + druidWebService.lastUrl
Maybe you forgot to delete it?

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/test/groovy/com/yahoo/wiki/webservice/web/endpoints/AutomaticDruidConfigLoaderSpec.groovy
> +            println "No response for " + druidWebService.lastUrl
Maybe you forgot to delete this?

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/dimension/GenericDimensionConfigs.java
> +        ;
What's this for?

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/dimension/GenericDimensionConfigs.java
> +     * @param dataSourceConfiguration the datasource configuration's dimensions to load
Two spaces before description. Capitalize `the`

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/main/java/com/yahoo/wiki/webservice/data/config/table/GenericTableLoader.java
> +import java.util.*;
Avoid start import

2017-06-01 19:22 UTC, QubitPi commented on fili-generic-example/src/test/groovy/com/yahoo/wiki/webservice/web/endpoints/MultipleDatasourceDruidConfigLoaderSpec.groovy
> +"""
Align indentation

2017-06-02 21:02 UTC, michael-mclawhorn approved these changes
Looks pretty good

2017-06-06 18:25 UTC, ghost approved these changes

2017-06-06 21:25 UTC, cdeszaq reviewed
Partial review. Didn't get as far as `GenericDimensionConfigs`.

2017-06-08 13:26 UTC, kevinhinterlong commented on fili-generic-example/README.md
> +`bard__ui_druid_broker`, `bard__druid_coord`, and other properties as needed.
Yep these are set correctly for running it locally and they work with the wikipedia walkthrough. 

I added the following note in `README.md` to clarify:

> **NOTE:** if you're running this locally and haven't changed any settings (like the Wikipedia example) you can **skip step 3**.

2017-06-09 18:36 UTC, kevinhinterlong commented
I added a note in the readme of the version this was last tested with. 
I think this should be good to merge now.

2017-06-22 18:08 UTC, garyluoex approved these changes
Rebase, and Im ok with it

2017-06-22 18:30 UTC, merged