Chinese translation
yahoo/fili pull request #398
Opened 2017-06-13 19:05 UTC by saiyan86

finished Chinese translation for Markdown file.

2017-06-13 21:38 UTC, ghost requested changes
Looks like org-mode doesn't parse to generate correct content somewhere. @garyluoex @michael-mclawhorn @cdeszaq What's your thoughts?

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<li><a href="#">1.2. 使用简介</a></li>
`href="#"` doesn't link to the actual section

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<li><a href="#">1.3. 版本</a>
`href="#"` doesn't link to the actual section

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<li><a href="#">1.4. 下载</a></li>
`href="#"` doesn't link to the actual section

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<li><a href="#">1.5. 扩展</a></li>
`href="#"` doesn't link to the actual section

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +标注了=@Deprecated=的API将在后续的发布中移除。过时的API会被维护一个发布周期，届时请尽快更新API。API不再维护之后随时会被清除。
Why do we add "=" around `@Deprecated` ?

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<td class="left">Dimension joins (both annotation and filtering)</td>
This is rendered wrongly.

2017-06-13 21:38 UTC, QubitPi commented on README-zh.md
> +<td class="left">[Rich usage metrics](monitoring-and-operations.md)</td>
This is rendered wrongly

2017-06-14 16:03 UTC, michael-mclawhorn commented
@QubitPi  I'm not sure I understand what you're referring to by 'org-mode'

2017-07-25 20:10 UTC, closed without merging

2017-07-25 20:10 UTC, QubitPi commented
duplicate of https://github.com/yahoo/fili/pull/444