Add custom dimension row serializer
yahoo/fili pull request #399
Opened 2017-06-14 16:12 UTC by garyluoex

2017-06-14 16:20 UTC, ghost requested changes

2017-06-14 16:20 UTC, QubitPi commented on fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/DimensionRowSerializer.java
> +    public void serialize(DimensionRow value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
Why do we throw exception at method level?

2017-06-14 16:35 UTC, michael-mclawhorn reviewed
Nothing much at issue here.

2017-06-14 16:35 UTC, michael-mclawhorn commented on fili-core/src/test/groovy/com/yahoo/bard/webservice/data/dimension/DimensionRowSpec.groovy
> +    }
Is this test resilient about map key order?  Are we guaranteeing that anywhere?

2017-06-14 16:35 UTC, michael-mclawhorn commented on CHANGELOG.md
> +
spelling: 'dimension rows serialize' or 'each dimension row serializes'

2017-06-14 19:04 UTC, garyluoex commented on fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/DimensionRowSerializer.java
> +    public void serialize(DimensionRow value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
```java    
public abstract void serialize(T value, JsonGenerator gen, SerializerProvider serializers)
        throws IOException, JsonProcessingException;
```

2017-06-15 13:18 UTC, kevinhinterlong commented on fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/DimensionRowSerializer.java
> +// Copyright 2016 Yahoo Inc.
2017

2017-06-15 15:42 UTC, michael-mclawhorn commented on fili-core/src/main/java/com/yahoo/bard/webservice/data/dimension/DimensionRowSerializer.java
> +    public void serialize(DimensionRow value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
My total bad.  I'm not sure if I was looking at the wrong javadoc, but I see in 2.2 for the fasterxml code, these are thrown.
I swear that I saw a version somewhere where there were not explicit throws.

2017-06-15 15:43 UTC, michael-mclawhorn approved these changes
👍

2017-06-19 16:52 UTC, michael-mclawhorn commented on CHANGELOG.md
> +
I suggest you move this to a fix and describe that this resolves where dimension field names do not serialize correctly.

2017-06-19 16:54 UTC, michael-mclawhorn commented on fili-core/src/test/groovy/com/yahoo/bard/webservice/data/dimension/DimensionRowSpec.groovy
> +        setup:
'correct format we expect' is redundant.  
Perhaps 'all expected fields and values are present in the dimension row serialization'

2017-06-19 16:54 UTC, michael-mclawhorn reviewed
My approval stands, but I've added a few more suggestions for improvement.

2017-08-29 16:44 UTC, michael-mclawhorn commented
@QubitPi could you rereview please and update any comments?

2019-04-11 17:28 UTC, closed without merging