Fix unexpected error messaging on DimensionServlet
yahoo/fili pull request #425
Opened 2017-07-12 21:07 UTC by michael-mclawhorn

Errors during dimension servlet processing were not printing stack traces

2017-07-12 21:28 UTC, kevinhinterlong approved these changes

2017-07-13 13:57 UTC, ghost requested changes

2017-07-13 13:57 UTC, QubitPi commented on CHANGELOG.md
> +- [Log stack trace at error on unexpected DimensionServlet failures]()
Link URL is missing

2017-07-13 14:04 UTC, ghost requested changes

2017-07-13 14:04 UTC, QubitPi commented on CHANGELOG.md
> +- [Log stack trace at error on unexpected DimensionServlet failures]()
Latest changes all appear to be at the top of list

2017-07-13 15:43 UTC, kevinhinterlong commented on CHANGELOG.md
> +- [Log stack trace at error on unexpected DimensionServlet failures]()
Maybe document 

> Latest changes all appear to be at the top of list

 in the [CHANGELOG process](https://github.com/yahoo/fili/pull/426)?

2017-07-21 21:03 UTC, ghost approved these changes

2017-08-17 20:08 UTC, garyluoex approved these changes

2017-08-17 20:08 UTC, merged